services:
  congrejw-angular:
    image: upwebcomar/congrejw-angular:latest
    container_name: congrejw-angular
    restart: always
    ports:
      - 4000:80

    environment:
      - VIRTUAL_HOST=congrejw.upweb.com.ar
      - LETSENCRYPT_HOST=congrejw.upweb.com.ar
      - LETSENCRYPT_EMAIL=freedomotica@gmail.com
      - API_URL=http://localhost:3000
      - APP_NAME=Congrejw
      - ALLOWED_DOMAINS=http://localhost
      - DISALLOWED_ROUTES=http://localhost/auth/login

    # command: /bin/sh -c "/start.sh" # configura variable de entorno para sw.js y env.js
    command: /bin/sh -c "ls -l /start.sh && cat -A /start.sh && /start.sh"

    networks:
      - proxy

networks:
  proxy:
    external: true
    name: my_network
